# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f255cbd7af054fdb55cc3902dfce99a099f12420a70c309a23742e01c0bcd7ed72a59669bb94c1c7bb1f605e150389a13a186b7701fdba971a414cdab20bb4dd

test:
  secret_key_base: 1d176bdc736b66958a0cac97659ec1aae0d6c98fb5d962955407fc2226283c1689252559a7e7ad5dd45d331141dad0811bcc3950b5d7658ab236081428fff00c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
